name: Production DB Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - 'sql/**'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Flyway Migrate
        run: |
          echo "ğŸš€ å¼€å§‹å®‰å…¨éƒ¨ç½²æ•°æ®åº“..."
          /usr/local/bin/flyway migrate \
            -url="jdbc:postgresql://${{ secrets.DB_HOST }}:5432/postgres" \
            -user="${{ secrets.DB_USER }}" \
            -password="${{ secrets.DB_PASSWORD }}" \
            -locations="filesystem:sql"
